### ISSUE TITLE
pluralsight.com : NativeScript Animation Techniques demo - rps-conf-ng

### ISSUE THREAD

**Issue by tosam** [alexziskind1/courses-rps-conference-app-ng#1]
Hi Alex,

I was trying to run the demo for above course but constantly getting below error, Please can you guide on below errors : 

λ tns --version
3.0.0

λ node --version
v6.9.1

-------------------------------------------------------------------------------------------------------------------
ERROR:
-------------------------------------------------------------------------------------------------------------------

λ tns run android
Executing before-prepare hook from D:\_DEV\NativeScript-Projects\rps-conf-ng\hooks\before-prepare\nativescript-dev-typescript.js Found peer TypeScript 2.3.2
node_modules/tns-core-modules/declarations.d.ts(3,15): error TS2300: Duplicate identifier 'Request'.

node_modules/tns-core-modules/declarations.d.ts(17,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'string[] | Headers | { [index: string]: string; }'.

node_modules/tns-core-modules/declarations.d.ts(32,14): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/tns-core-modules/declarations.d.ts(33,14): error TS2300: Duplicate identifier 'RequestCredentials'.

node_modules/tns-core-modules/declarations.d.ts(34,14): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/tns-core-modules/declarations.d.ts(36,15): error TS2300: Duplicate identifier 'Headers'.
node_modules/tns-core-modules/declarations.d.ts(46,5): error TS2687: All declarations of 'bodyUsed' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(56,15): error TS2300: Duplicate identifier 'Response'.

node_modules/tns-core-modules/declarations.d.ts(69,14): error TS2300: Duplicate identifier 'ResponseType'.
node_modules/tns-core-modules/declarations.d.ts(72,5): error TS2687: All declarations of 'status' must have identical modifiers. node_modules/tns-core-modules/declarations.d.ts(73,5): error TS2687: All declarations of 'statusText' must have identical modifiers.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'headers' must be of type 'any', but here has type 'HeaderInit'.
node_modules/tns-core-modules/declarations.d.ts(74,5): error TS2687: All declarations of 'headers' must have identical modifiers.

node_modules/tns-core-modules/declarations.d.ts(78,14): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/tns-core-modules/declarations.d.ts(79,14): error TS2300: Duplicate identifier 'RequestInfo'.

node_modules/typescript/lib/lib.d.ts(11216,11): error TS2300: Duplicate identifier 'Headers'.

node_modules/typescript/lib/lib.d.ts(11225,13): error TS2300: Duplicate identifier 'Headers'.
node_modules/typescript/lib/lib.d.ts(13614,11): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.d.ts(13631,13): error TS2300: Duplicate identifier 'Request'.
node_modules/typescript/lib/lib.d.ts(13636,11): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.d.ts(13647,13): error TS2300: Duplicate identifier 'Response'.
node_modules/typescript/lib/lib.d.ts(19206,6): error TS2300: Duplicate identifier 'BodyInit'.
node_modules/typescript/lib/lib.d.ts(19237,6): error TS2300: Duplicate identifier 'RequestInfo'.
node_modules/typescript/lib/lib.d.ts(19305,6): error TS2300: Duplicate identifier 'RequestCache'.
node_modules/typescript/lib/lib.d.ts(19306,6): error TS2300: Duplicate identifier 'RequestCredentials'.
node_modules/typescript/lib/lib.d.ts(19308,6): error TS2300: Duplicate identifier 'RequestMode'.
node_modules/typescript/lib/lib.d.ts(19311,6): error TS2300: Duplicate identifier 'ResponseType'.

Thanks & Regards,
SamA

**Comment by alexziskind1** [comment]
Hi Sam. This demo is set up for NativeScript 2.5 and is not yet updated with the configs for NativeScript 3.0.
You can create another project and copy the updated package.json settings and the tsconfig.json setting into your courses-rps-conference-app-ng demo app. That should help you get moving.

**Comment by tosam** [comment]
Hi Alex,

Thanks for quick reply, After walking through the code found many deprecated templates are used I can understand it is a good amount of work to correct everything. ;)... I will be early waiting for the new release, Please update once you upload the new version.   

-Cheers

**Comment by alexziskind1** [comment]
Hi @tosam . Check out the new branch if you haven't yet upgraded yourself.
